# Generated by Django 3.0.2 on 2022-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220220_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='verfication_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
