# Generated by Django 3.0.2 on 2022-03-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_coupen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='paper_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_type', to='services.Paper_type'),
        ),
    ]
