# Generated by Django 3.0.2 on 2022-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20220308_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='media_file_coordinator',
            field=models.FileField(default=1, upload_to='media/coordinator_mediafile'),
            preserve_default=False,
        ),
    ]
